### ISSUE TITLE
Taiyō city move

### ISSUE THREAD

**Issue by ImACoolTree** [turtlebyturtle/turtlebyturtle.github.io#16]
Sekas Civic move to fit on the map
![image](https://user-images.githubusercontent.com/99458471/153730442-245571ff-f935-403f-a3d3-7ff57521b968.png)

**Comment by turtlebyturtle** [comment]
Done
![image](https://user-images.githubusercontent.com/35892176/153800002-ef4dabb3-5f84-4733-be24-fde992404900.png)
